# In this section we add the repos that contain the hooks that we need to work
# We have to follow the next steps in this order:

# 1.- Add the url of the repository
# 2.- Add the tag version that we want to work with
# 3.- Add the id of the hooks that we want to implement into our project


repos:
# Most common hooks, from pre-commit-hooks base repository
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
      - id: pretty-format-json
      - id: check-merge-conflict
#      - id: check-toml
#      - id: check-yaml
##      - id: double-quote-string-fixer
#      - id: end-of-file-fixer
#      - id: mixed-line-ending
#      - id: name-tests-test
#      - id: no-commit-to-branch
#      - id: requirements-txt-fixer
#      - id: trailing-whitespace
#
## Another group of hooks that we'll like to add to work with in our project
#
#
## Black, most popular code Python code formatter
##  - repo: https://github.com/psf/black
##    rev: 20.8b1
##    hooks:
##      - id: black
#
#
## Bandit, tool designed to find common security issues
##  - repo: https://github.com/PyCQA/bandit
##    rev: 1.7.0
##    hooks:
##      - id: bandit
#
#
## Pylint, Python tool to detect coding mistakes, force to follow code
## standards, find code smells and offer refactoring suggestions
##  - repo: https://github.com/PyCQA/pylint
##    rev: pylint-2.7.4
##    hooks:
##      - id: pylint
#
#
### Codespell, fix common misspelling
##  - repo: https://github.com/codespell-project/codespell
##    rev: v2.0.0
##    hooks:
##      - id: codespell
#
#
## Dead, simple python dead code detection
##  - repo: https://github.com/asottile/dead
##    rev: v1.4.0
##    hooks:
##      - id: dead
#
#
### Autopep8, formats Python code to conform to the PEP 8 style guide
##  - repo: https://github.com/pre-commit/mirrors-autopep8
##    rev: v1.5.6
##    hooks:
##      - id: autopep8
#
#
## Flake8, is a great toolkit for checking your code base against the coding style (PEP8)
##  - repo: https://gitlab.com/pycqa/flake8
##    rev: 3.9.0
##    hooks:
##      -   id: flake8